// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxlsrzucqkwggexknkyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4bHNyenVjcWt3Z2dleGtua3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzAzNjYsImV4cCI6MjA3MTAwNjM2Nn0.D5-KAt3tmHiSFUJu52BPjNQxBUcPYifKXcmMgIDtYIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});